services:
  - type: web
    name: ig-reels-mp3-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python apnahihai.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
